[package]
name = "etherscan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.75"
serde_with = "1.11.0"
thiserror = "1.0.30"
tokio = { version = "1", features = ["macros"]}